parser: babel-eslint
env:
  browser: true
  node: true
  commonjs: true
  es6: true
globals:
  System: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
